#!/usr/bin/env bash
# ============================================================
# AlliGo / Zaia — FULL MACHINE RECOVERY SCRIPT
# Run this after a wipe. Gets everything back in ~3 minutes.
#
# Usage:
#   curl https://raw.githubusercontent.com/spiritclawd/AlliGo/master/RECOVER.sh | bash
#   OR: bash /home/computer/alligo/RECOVER.sh
#
# Prerequisites (Carlos provides via Railway):
#   - ALLIGO_ADMIN_KEY
#   - OPENROUTER_API_KEY
#   - GROQ_API_KEY
#   - TELEGRAM_BOT_TOKEN
#   - AGENTMAIL_API_KEY
#   - GITHUB_PAT
#   - EAS_PRIVATE_KEY
#   - TASKMARKET_API_TOKEN
#   - TASKMARKET_PRIVATE_KEY
#   - TASKMARKET_DEVICE_ID
# ============================================================

set -e
PYTHON=/usr/local/share/python-default/bin/python3
BUN=~/.bun/bin/bun
COMPUTER_HOME=/home/computer

echo "╔══════════════════════════════════════════════════════╗"
echo "║        AlliGo / Zaia — Machine Recovery v1.0        ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── STEP 1: Clone AlliGo repo ──────────────────────────────
echo "▶ Step 1: Clone AlliGo repo..."
if [ -d "$COMPUTER_HOME/alligo" ]; then
  echo "  alligo/ already exists, pulling latest"
  cd "$COMPUTER_HOME/alligo" && git pull origin master
else
  cd "$COMPUTER_HOME"
  # Try deploy key first, fallback to GITHUB_PAT
  if [ -f ~/.ssh/github_deploy_key ]; then
    GIT_SSH_COMMAND="ssh -i ~/.ssh/github_deploy_key -o StrictHostKeyChecking=no" \
      git clone git@github.com:spiritclawd/AlliGo.git alligo
  elif [ -n "$GITHUB_PAT" ]; then
    git clone "https://$GITHUB_PAT@github.com/spiritclawd/AlliGo.git" alligo
  else
    echo "  ERROR: No git credentials. Set GITHUB_PAT or restore ~/.ssh/github_deploy_key"
    exit 1
  fi
fi
echo "  ✅ Repo ready"

# ── STEP 2: Rebuild SSH deploy key ────────────────────────
echo ""
echo "▶ Step 2: SSH deploy key..."
if [ ! -f ~/.ssh/github_deploy_key ]; then
  echo "  ⚠️  Deploy key missing. Manual step:"
  echo "     Get the private key from Railway env var GITHUB_DEPLOY_KEY"
  echo "     Then: echo \$GITHUB_DEPLOY_KEY > ~/.ssh/github_deploy_key && chmod 600 ~/.ssh/github_deploy_key"
  echo "  (Skipping for now — PAT-based push will work as fallback)"
else
  chmod 600 ~/.ssh/github_deploy_key
  echo "  ✅ Deploy key present"
fi

# ── STEP 3: Create zaia-swarm directory ───────────────────
echo ""
echo "▶ Step 3: Set up zaia-swarm..."
SWARM_DIR="$COMPUTER_HOME/zaia-swarm"
mkdir -p "$SWARM_DIR/agents" "$SWARM_DIR/config" "$SWARM_DIR/data" "$SWARM_DIR/logs"

# Sync from alligo repo (source of truth)
cp -r "$COMPUTER_HOME/alligo/packages/swarm/agents/." "$SWARM_DIR/agents/"
cp "$COMPUTER_HOME/alligo/packages/swarm/swarm.py" "$SWARM_DIR/"
cp "$COMPUTER_HOME/alligo/packages/swarm/config/swarm.json" "$SWARM_DIR/config/"
echo "  ✅ Swarm files synced from repo"

# ── STEP 4: Write .env from Railway vars ──────────────────
echo ""
echo "▶ Step 4: Writing .env..."
cat > "$SWARM_DIR/.env" << ENVEOF
# AlliGo Zaia Swarm — Environment Variables
# Auto-generated by RECOVER.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

ALLIGO_API=https://alligo-production.up.railway.app
ALLIGO_ADMIN_KEY=${ALLIGO_ADMIN_KEY:?REQUIRED}

# LLM — OpenRouter primary, Groq fallback
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:?REQUIRED}
GROQ_API_KEY=${GROQ_API_KEY:?REQUIRED}

# Integrations
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:?REQUIRED}
AGENTMAIL_API_KEY=${AGENTMAIL_API_KEY:?REQUIRED}
GITHUB_PAT=${GITHUB_PAT:?REQUIRED}

# EAS — onchain (fund wallet before enabling)
EAS_MODE=${EAS_MODE:-offchain}
EAS_SCHEMA_UID=0xb7c0c403941bfa822940a27602e8b9350904b5a13e0ed291f2ccc3d92dc974ba
EAS_ATTESTER_ADDRESS=0x9F810067eA679aBBF3A0726aFC858d6314D56892
EAS_PRIVATE_KEY=${EAS_PRIVATE_KEY:?REQUIRED}
EAS_CONTRACT=0x4200000000000000000000000000000000000021

# TaskMarket / Daydreams
TASKMARKET_WALLET=0xA5aCaA6779377217Ac8fC0A988Aee62C956eEe13
TASKMARKET_AGENT_ID=33150
TASKMARKET_API_TOKEN=${TASKMARKET_API_TOKEN:?REQUIRED}
TASKMARKET_DEVICE_ID=7e9b2fc3-20d1-459d-abda-6c51afecd1f8
TASKMARKET_PRIVATE_KEY=${TASKMARKET_PRIVATE_KEY:?REQUIRED}

# LLM models
FORENSICS_MODEL=meta-llama/llama-3.3-70b-instruct
FORENSICS_MODEL_CHEAP=meta-llama/llama-3.1-8b-instruct
ENVEOF
echo "  ✅ .env written"

# ── STEP 5: Restore TaskMarket keystore ───────────────────
echo ""
echo "▶ Step 5: Restore TaskMarket keystore..."
KEYSTORE_DIR="$HOME/.taskmarket"
mkdir -p "$KEYSTORE_DIR"
if [ ! -f "$KEYSTORE_DIR/keystore.json" ] && [ -n "$TASKMARKET_PRIVATE_KEY" ]; then
  echo "  Importing wallet from TASKMARKET_PRIVATE_KEY..."
  cd "$SWARM_DIR"
  source .env
  npx --yes @lucid-agents/taskmarket wallet import --key "$TASKMARKET_PRIVATE_KEY" --yes 2>/dev/null || \
  npx --yes @lucid-agents/taskmarket wallet import "$TASKMARKET_PRIVATE_KEY" 2>/dev/null || \
  echo "  ⚠️  Manual import may be needed: npx @lucid-agents/taskmarket wallet import --key \$TASKMARKET_PRIVATE_KEY"
  if [ -f "$KEYSTORE_DIR/keystore.json" ]; then
    echo "  ✅ Keystore restored"
  else
    echo "  ⚠️  Keystore import failed — reviewer agent will auto-retry on first run"
  fi
else
  echo "  ✅ Keystore already present"
fi

# ── STEP 6: Restore initial data state ────────────────────
echo ""
echo "▶ Step 6: Restore data state from repo..."
DATA_REPO="$COMPUTER_HOME/alligo/packages/swarm/data"
if [ -d "$DATA_REPO" ]; then
  cp -r "$DATA_REPO/." "$SWARM_DIR/data/" 2>/dev/null && echo "  ✅ Data restored from repo snapshot" || echo "  ⚠️  No data snapshot in repo (fresh start)"
else
  # Create minimal required data files
  echo '{"active":[],"legacy":[{"id":"0xab58bacae3f206f145a9757ff2600e27a1ff8bb67d7d9bdc3204fd6cd4806722","status":"expired","note":"Old bounty, wallet wiped, unrecoverable"}],"new_wallet":"0xA5aCaA6779377217Ac8fC0A988Aee62C956eEe13","new_agentId":"33150"}' > "$SWARM_DIR/data/alligo_task_ids.json"
  echo '{"total_paid_usdc":0.0,"total_accepted":0,"total_rejected":1,"payments":[]}' > "$SWARM_DIR/data/payout_ledger.json"
  echo '{"count":0,"paused":false}' > "$SWARM_DIR/data/consec_rejections.json"
  echo "  ✅ Minimal data files created"
fi

# ── STEP 7: Install Python deps ───────────────────────────
echo ""
echo "▶ Step 7: Python dependencies..."
$PYTHON -m pip install -q agentmail web3 eth-abi 2>/dev/null && echo "  ✅ Python deps installed" || echo "  ⚠️  Some deps may be missing"

# ── STEP 8: Start the swarm ───────────────────────────────
echo ""
echo "▶ Step 8: Start swarm..."
if pgrep -f "swarm.py" > /dev/null; then
  echo "  ✅ Swarm already running (PID $(pgrep -f swarm.py | head -1))"
else
  cd "$SWARM_DIR"
  source .env
  nohup $PYTHON swarm.py >> logs/swarm_main.log 2>&1 &
  SWARM_PID=$!
  sleep 3
  if kill -0 $SWARM_PID 2>/dev/null; then
    echo "  ✅ Swarm started (PID $SWARM_PID)"
  else
    echo "  ❌ Swarm failed to start — check logs/swarm_main.log"
  fi
fi

# ── STEP 9: Verify production ─────────────────────────────
echo ""
echo "▶ Step 9: Verify production..."
HEALTH=$(curl -s https://alligo-production.up.railway.app/health 2>/dev/null)
if echo "$HEALTH" | grep -q '"status":"ok"'; then
  CLAIMS=$(echo "$HEALTH" | $PYTHON -c "import json,sys; h=json.load(sys.stdin); print(h.get('claims','?'))" 2>/dev/null)
  CAL=$(echo "$HEALTH" | $PYTHON -c "import json,sys; h=json.load(sys.stdin); print(h.get('calibration',{}).get('status','?'))" 2>/dev/null)
  echo "  ✅ Production healthy — claims=$CLAIMS calibration=$CAL"
else
  echo "  ⚠️  Production unreachable or unhealthy"
fi

# ── DONE ──────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║                  Recovery complete!                  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  tail -f $SWARM_DIR/logs/swarm_main.log   # watch swarm"
echo "  curl -s https://alligo-production.up.railway.app/health | python3 -m json.tool"
echo ""
echo "Still needs Carlos (from Railway env vars):"
echo "  - All REQUIRED env vars above"
echo "  - EAS wallet ETH top-up if EAS_MODE=onchain: 0x9F810067eA679aBBF3A0726aFC858d6314D56892"
echo "  - USDC to 0xA5aCaA6779377217Ac8fC0A988Aee62C956eEe13 for new TaskMarket bounty"
